apiVersion: v1
kind: Service
metadata:
  name: react
  labels:
    app: react
spec:
  type: NodePort
  ports:
    - nodePort: 31000
      port: 3000
      targetPort: 3000
  selector:
    app: react
---

apiVersion: v1
kind: Pod
metadata:
  name: react
  labels:
    app: react
spec:
  containers:
  - name: react
    image: druce080/flaskcolor
    ports:
    - containerPort: 3000
